topic:
  event: eventBlaas
  recordMap: recordMapBlaas
  notify: notifyBlaas
redis:
  host: gg
  port: 6379
networkConfig:
  miniBatchSize: 32
  seed: 120
  iterations: 1
  learningRate: 0.0015
  nEpochs: 600
  hidden: 10
dataDirectory: C:/Users/gg
retry:
  maxCount: 2
  timeoutInSeconds: 10